# Generated by Django 5.0.6 on 2024-07-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_transaction_date_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.CharField(default='https://www.pinterest.com/', max_length=500),
        ),
    ]
