# Generated by Django 5.0.6 on 2024-07-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_img_url'),
    ]

    operations = [
    ]
